<?php

########################################################################
# Extension Manager/Repository config file for ext: "mdrmanager"
#
# Auto generated by Extension Builder 2012-06-22
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MijnDomeinReseller Manager',
	'description' => 'Manage your MijnDomeinReseller domains with TYPO3',
	'category' => 'plugin',
	'author' => 'Lars Nieuwenhuizen',
	'author_email' => 'lars.nieuwenhuizen@me.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>